---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-1
  name: hello-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-1
    spec:
      containers:
      - env:
        - name: MONGODB_IP
          value: px-mongo-mongodb
        - name: MONGODB_USER
          value: my-user
        - name: MONGODB_PASSWORD
          value: my-password
        image: eu.gcr.io/revoluttest-223208/rhello:v1
        imagePullPolicy: Always
        name: rhello
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

